#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinx_issues
Version  : 3.0.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/00/35/a50591c1242d3f3927bcfd0e967c2858fef8fdb50f25b742015b6c841e03/sphinx-issues-3.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/00/35/a50591c1242d3f3927bcfd0e967c2858fef8fdb50f25b742015b6c841e03/sphinx-issues-3.0.1.tar.gz
Summary  : A Sphinx extension for linking to your project's issue tracker
Group    : Development/Tools
License  : MIT
Requires: pypi-sphinx_issues-python = %{version}-%{release}
Requires: pypi-sphinx_issues-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(sphinx)

%description
=============
sphinx-issues
=============
.. image:: https://badgen.net/pypi/v/sphinx-issues
:alt: pypi badge
:target: https://pypi.org/project/sphinx-issues/

%package python
Summary: python components for the pypi-sphinx_issues package.
Group: Default
Requires: pypi-sphinx_issues-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_issues package.


%package python3
Summary: python3 components for the pypi-sphinx_issues package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_issues)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_issues package.


%prep
%setup -q -n sphinx-issues-3.0.1
cd %{_builddir}/sphinx-issues-3.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642461300
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
